from backend.utils.llm import LLM
from backend.agents.base_agent import BaseAgent


class BAAgent(BaseAgent):
    def __init__(self, model_name, temperature, inputs: dict):
        super().__init__(model_name=model_name, temperature=temperature)
        self.inputs = inputs

    def process(self) -> str:
        """
        Generate code based on the requirements.

        Args:
            requirements (str): The requirements to base the code generation on.

        Returns:
            str: The code generated by the LLM.
        """
        prompt = (
            f"Based on the following inputs: {self.inputs}\n"
            "Generate the requirements in the following format:\n"
            ""
        )
        return self.llm.generate_response()
