from backend.utils.llm import LLM


class DevAgent:
    def __init__(self):
        self.llm = LLM(model_name="gpt-4")

    def generate_code(self, requirements: str) -> str:
        """
        Generate code based on the requirements.

        Args:
            requirements (str): The requirements to base the code generation on.

        Returns:
            str: The code generated by the LLM.
        """
        prompt = (
            f"Generate Python code for the following requirements:\n\n{requirements}"
        )
        return self.llm.generate_response(prompt, max_tokens=500)
