from abc import ABC, abstractmethod


class AgentInterface(ABC):
    """
    Interface that all agents must implement.
    """

    @abstractmethod
    def process(self, input_data: str) -> str:
        """
        Process the input data and return a response.

        Args:
            input_data (str): The input data for the agent.

        Returns:
            str: The response generated by the agent.
        """
        pass
